### ISSUE TITLE
Required memory to run Tox 21 notebook example?

### ISSUE THREAD

**Issue by paconius** [deepchem/deepchem#1150]
I just setup deepchem on ubuntu using the recommended python env (python 3.5, tensorflow-gpu v1.5.0, CUDA 9.0, cuDNN 7.0). I am trying to run the "graph_convolutional_networks_for_tox21" notebook and immediately run into an issue that appears to be an out-of-memory situation on imput line 3. The  console show two error types (see below) that google searching have shown to be associated with full GPU memory.

I'm taking from this that a GeForce GTX 1060 6GB is not sufficient for this calculation. Can anyone let me know what the minimal GPU setup would be to run this and other similar calculations?

Thanks.

Log:
I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5335 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-03-13 19:03:19.581659: E tensorflow/stream_executor/cuda/cuda_blas.cc:443] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
....repeats about 50x.....
W tensorflow/stream_executor/stream.cc:1901] attempting to perform BLAS operation using StreamExecutor without BLAS support
...repeats about 4x...
Finally stops and python gives this error: InternalError: Blas GEMM launch failed : ...

**Comment by evanfeinberg** [comment]
Thanks for your interest. From a diagnostic perspective I would open a terminal and run "watch nvidia-smi" to monitor GPU memory usage; if it indeed appears to be the case that GPU memory is oversubscribed, try decreasing the batch size to see if that helps.

**Comment by paconius** [comment]
Hi. I was watching the GPU memory usage with nvidia-smi. I note that the memory immediately jumps to full consumption upon start of the calculation. It does not move after that point.

**Comment by evanfeinberg** [comment]
Can you try reducing the batch size to see if it runs?

**Comment by paconius** [comment]
I reduced batch size from 50 to 10 and then to 2 and observe the same behavior.

**Comment by evanfeinberg** [comment]
Thanks for trying. That is indeed quite strange. I would recommend seeing
if you can replicate this issue with a simpler notebook, e.g.
https://github.com/deepchem/deepchem/blob/master/examples/notebooks/solubility.ipynb

**Comment by paconius** [comment]
Thank you for your input. I tried running the solubility notebook and get a different error which suggests my problems go deeper.

AttributeError: module 'deepchem.models' has no attribute 'TensorflowMultiTaskRegressor'

An older posting here suggested that this is due to an out-of date install of deepchem. However, I just installed it today using conda. Running: conda install -c deepchem deepchem-gpu=2.0.0c confirms that this version is installed

**Comment by evanfeinberg** [comment]
Glad the debugging process revealed what I suspected, which is a deeper issue at play. I would open a jupyter notebook, run ```import deepchem''' and then ```deepchem.__version__''' or ```deepchem.__file__''' and make sure it's loading the correct deepchem version. I suspect you have a conflicting older version lying around that you should get rid of somehow.

**Comment by evanfeinberg** [comment]
*fixed formatting

**Comment by paconius** [comment]
I don't believe I have an old version. My install is on a fresh ubuntu machine. I uninstalled confirmed no other copies were on the drive. I even emptied the pkg cache in anaconda. I reinstalled using conda install -c deepchem deepchem-gpu=2.0.0 and still have the same problems.

**Comment by paconius** [comment]
Here is an interesting tidbit: With regard to this error:

AttributeError: module 'deepchem.models' has no attribute 'TensorflowMultiTaskRegressor'

If I peek inside the deepchem.models module I see the correct attribute, but the capitalization is different. The 't' in task is lower case.

print(dir(deepchem.models))
['ANIRegression', 'BPSymmetryFunctionRegression', 'DAGTensorGraph', 'DTNNTensorGraph', 'GAN', 'GraphConvTensorGraph', 'MPNNTensorGraph', 'Model', 'MultiTaskClassifier', 'MultiTaskFitTransformRegressor', 'MultiTaskRegressor', 'ProgressiveMultitaskRegressor', 'RobustMultitaskClassifier', 'RobustMultitaskRegressor', 'SeqToSeq', 'SequenceDNN', 'Sequential', 'SingletaskToMultitask', 'SklearnModel', 'TensorGraph', 'TensorflowMultiTaskIRVClassifier', 'TextCNNTensorGraph', 'WGAN', 'WeaveTensorGraph', 'XGBoostModel', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'division', 'models', 'multitask', 'sklearn_models', 'tensorgraph', 'unicode_literals', 'xgboost_models']

**Comment by paconius** [comment]
Okay. I changed the notebook to use  'MultiTaskRegressor' instead of  'TensorflowMultiTaskRegressor' because I concluded that the notebook is no longer up-to-date and does not function as published. Making this change allows the code to run, however,  I immediately observe the same errors and memory issues that I observed with the Tox21 example.

**Comment by rbharath** [comment]
Could this be related to #1133? I haven't observed these memory leaks personally, and our Jenkins runs seem to be working fine, so perhaps there are some combinations of hardware/software where it becomes an issue?

**Comment by paconius** [comment]
Thanks for you help with this. I found that I was able to make the code work correctly if I run as root. This is awkward, but it works. There must be some permissions issue with CUDA.

**Comment by paconius** [comment]
Now able to run as a normal user without sudo. The answer was found [here.](https://devtalk.nvidia.com/default/topic/1007071/cuda-setup-and-installation/cuda-error-when-running-matrixmulcublas-sample-ubuntu-16-04/2) he solution is to run:
sudo rm -rf ~/.nv/ 

What does it do and why? I have no idea.

**Comment by evanfeinberg** [comment]
So glad you got it working! Happy deepchem’ing.

Bharath and I are HTH

**Comment by peastman** [comment]
It sounds like that directory is some sort of a cache.  Presumably its contents must have gotten messed up in some way?

**Comment by rbharath** [comment]
Closing the issue since it looks to have been resolved.
