### ISSUE TITLE
DeepChem Windows Support

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1486]
At present DeepChem doesn't support Windows installs. As the book moves closer to publication though, it will become important for us to support Windows otherwise readers who use windows won't be able to do any of the examples. Windows support should be in place for the next DeepChem release.

**Comment by abster12** [comment]
If you don't mind me asking could please tell me what exactly needs to be done to add windows support?

**Comment by peastman** [comment]
I'm not sure what, if anything, doesn't work on Windows at this point.  I would just try it out and see what breaks.

**Comment by abster12** [comment]
Other than installing from source is there any other way to install deepchem? It seems i cannot run the same commands in the readme to install from source on windows

**Comment by peastman** [comment]
Current it needs to be installed from source.  Once everything is working correctly, the next step will be to build conda packages for Windows.

**Comment by abster12** [comment]
Yeah I tried using the instructions given but I got these errors.
``` scripts/install_deepchem_conda.sh: line 3: $'\r': command not found
scripts/install_deepchem_conda.sh: line 7: $'\r': command not found
scripts/install_deepchem_conda.sh: line 12: syntax error near unexpected token `elif'
'cripts/install_deepchem_conda.sh: line 12: `elif [ "$gpu" == 1 ] ```

**Comment by abster12** [comment]
The only way I got it to run was run ``` python setup.py install``` and after that i had to install a few other packages and I could get a tutorial running.

**Comment by peastman** [comment]
install_deepchem_conda.sh is a Unix shell script.  It won't work on Windows.  You'll need to install all the dependencies by hand.

> after that i had to install a few other packages and I could get a tutorial running.

That's a good start!  Next thing to try is running the full test suite:

```
nosetests deepchem
```

**Comment by abster12** [comment]
How do I deal with the benchmarking on dataset errors?

**Comment by abster12** [comment]
Also the tests for weave models and dag regressionn models fail.

**Comment by peastman** [comment]
> How do I deal with the benchmarking on dataset errors?

What do you mean?

> Also the tests for weave models and dag regressionn models fail.

What are the error messages?

**Comment by abster12** [comment]
Benchmarking errors like these : 
``` ======================================================================
ERROR: Tests molnet benchmarking on delaney with graphconvreg.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\molnet\tests\test_molnet.py", line 46, in test_delaney_graphconvreg
    assert lastrow[-4] == 'valid'
IndexError: list index out of range
-------------------- >> begin captured stdout << ---------------------
-------------------------------------
Benchmark on dataset: delaney
-------------------------------------
Splitting function: random
Loading raw samples now.
shard_size: 8192
About to start loading CSV from C:\Users\abhig\AppData\Local\Temp\delaney-processed.csv
Loading shard 1 of size 8192.
Featurizing sample 0
Featurizing sample 1000
TIMING: featurizing shard 0 took 1.127 s
TIMING: dataset construction took 1.426 s
Loading dataset from disk.
TIMING: dataset construction took 0.396 s
Loading dataset from disk.
TIMING: dataset construction took 0.360 s
Loading dataset from disk.
TIMING: dataset construction took 0.173 s
Loading dataset from disk.
TIMING: dataset construction took 0.176 s
Loading dataset from disk.
-----------------------------
Start fitting: graphconvreg
computed_metrics: [0.9930457704061578]
computed_metrics: [0.88944751760557]'''

``` ======================================================================
ERROR: Tests molnet benchmarking on qm7 with multitask network.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\molnet\tests\test_molnet.py", line 64, in test_qm7_multitask
    reload=False)
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\molnet\run_benchmark.py", line 154, in run_benchmark
    featurizer=featurizer, split=split, reload=reload)
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\molnet\load_function\qm7_datasets.py", line 87, in load_qm7_from_mat
    dataset)
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\splits\splitters.py", line 153, in train_valid_test_split
    train_dataset = dataset.select(train_inds, train_dir)
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\data\datasets.py", line 1254, in select
    generator(), data_dir=select_dir, tasks=tasks, verbose=self.verbose)
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\data\datasets.py", line 565, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\data\datasets.py", line 1237, in generator
    y_sel = y[shard_inds]
IndexError: index 1 is out of bounds for axis 0 with size 1 ```

``` 
======================================================================
FAIL: test_weave_regression_model (deepchem.models.tensorgraph.tests.test_graph_models.TestGraphModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\models\tensorgraph\tests\test_graph_models.py", line 226, in test_weave_regression_model
    scores2['mean_absolute_error'])
AssertionError:
-------------------- >> begin captured stdout << ---------------------
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
computed_metrics: [0.0043231392402936384, 0.004276127215468772]
computed_metrics: [0.0043233515740886295, 0.004276177176361751]```

**Comment by abster12** [comment]
Other errors that I encountered was the tests not detecting the 'Bio' module even though it works outside of the tests. Also the test if logging can be invoked fails.
``` FAIL: Test that Log can be invoked.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\models\tensorgraph\tests\test_layers.py", line 339, in test_log
    assert np.array_equal(np.log(value), result)
AssertionError```

**Comment by peastman** [comment]
The next step is to debug those failures to figure out what's going on.  That will involve adding debugging code to get more information.  For example, consider the error in `test_delaney_graphconvreg()`.  Here's the code where it's failing:

```python
    with open(os.path.join(out_path, 'results.csv'), 'r') as f:
      reader = csv.reader(f)
      for lastrow in reader:
        pass
      assert lastrow[-4] == 'valid'
```

It just skims through the file to the last line and checks that it has the expected values in it.  That test is failing, perhaps indicating that the CSV reader isn't processing it correctly.  So print out `lastrow` and see what it actually contains.

Or consider the error in `test_weave_regression_model()`.  Here's the full code of that test case:

```python
  def test_weave_regression_model(self):
    tasks, dataset, transformers, metric = self.get_dataset(
        'regression', 'Weave')

    model = WeaveModel(len(tasks), mode='regression')

    model.fit(dataset, nb_epoch=80)
    scores = model.evaluate(dataset, [metric], transformers)
    assert all(s < 0.1 for s in scores['mean_absolute_error'])

    model.save()
    model = TensorGraph.load_from_dir(model.model_dir)
    scores2 = model.evaluate(dataset, [metric], transformers)
    assert np.allclose(scores['mean_absolute_error'],
                       scores2['mean_absolute_error'])
```

It trains a model, saves it to disk, and produces evaluation metrics from it.  Then it reloads the model from disk, evaluates the reconstructed version, and checks that it produces identical results.  That test is failing.  Possibly this indicates a problem in saving and loading models?  Or perhaps it's just an overly strict numeric tolerance?  The first thing to do is add code that prints out the values being compared:

```python
print(scores['mean_absolute_error'])
print(scores2['mean_absolute_error'])
```

See whether they're only slightly different or very different.  If they're very different, that suggests something is going wrong in the saving and loading.  So then you need to start instrumenting the routines that save and load to trace backward and figure out what's going wrong.

**Comment by abster12** [comment]
Okay , thanks for the help. I will get to it.

**Comment by JimSEOW** [comment]
@abster12 I recently succeeded in installing Anaconda Deepchem 2.1.0 to Windows 10 WSL (Ubuntu 18.04). Perhaps in your effort, could you also feedback on the remaining challenges of installing DeepChem 2.1.0 to Windows 10 without using WSL as it is essential to have tensorflow-GPU working through DeepChem. 

I also just checked that latest [XGBoost ](https://github.com/dmlc/xgboost/issues/4272#issue-422113081) can now be installed in Windows 10.

**Comment by abster12** [comment]
You could try installing it directly to windows using anaconda but you would have to clone the repository and run ``` python setup.py install ``` and after that you would have to install the dependencies seperately. After that you should get it running directly on windows without WSL and if you are using it in your work please let me know if you encounter any major problems.

**Comment by JimSEOW** [comment]
@abster12  from the discussion you had above, it is clear that currently there is no solution for 

>  installing it directly to windows using anaconda

![image](https://user-images.githubusercontent.com/8244633/54546010-1e65dd80-49a3-11e9-972f-addd98b7e4d3.png)

The whole point of having DeepChem available as Win64 in anaconda is that if anyone needs to promote DeepChem by organizing a workshop, it is a nice feature to have to allow participants to install deepchem in a more realiable way (including Windows user) through anaconda (e.g rdKit)
![image](https://user-images.githubusercontent.com/8244633/54546838-d2b43380-49a4-11e9-8105-9b16269a7961.png)

**Comment by peastman** [comment]
Once we're confident everything is working correctly on Windows we can create a conda package for it.  @abster12 try using the latest version of the code.  I recognize at least one of the errors reported above as being one I fixed in #1535.

**Comment by abster12** [comment]
Yeah the weave model tests are not showing errors now and I think there are a couple of other errors which are similar, I will try to add fixes and you could see if they are correct.
Some other errors that I encountered were that the tests for logging keeps failing and even though I have Biopython installed it still shows an import error for Bio.

**Comment by abster12** [comment]
Vina isn't available for windows so the tests related to that can't pass for now. I went through other errors and other than some flaky tests, molnet benchmarking tests are the only ones failing.

**Comment by abster12** [comment]
```

======================================================================
ERROR: Tests molnet benchmarking on clintox with multitask network.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abhig\OneDrive\Desktop\deepchem\deepchem\molnet\tests\test_molnet.py", line 92, in test_clintox_multitask
    assert lastrow[-4] == 'test'
IndexError: list index out of range
```
All the molnet show similar kind of errors and when trying to test seperately it isn't working on my computer right now. I'll keep trying but could tell me what does the lastrow list contain.

**Comment by peastman** [comment]
Here is what `lastrow` is supposed to equal:

```
['clintox', 'random', 'classification', 'tf', 'mean-roc_auc_score', 'train', '0.9915569652490531', 'valid', '0.7649419132284633', 'test', '0.7849218978636231', 'time_for_running', '3.28210711479187']
```

**Comment by JimSEOW** [comment]
@abster12  Here is the Visual Studio project solution to compile Vina for Win-64 
https://github.com/Ashod/vina/tree/master/build/win

**Comment by JimSEOW** [comment]
This is better, Anaconda distributed Win-64 Vina: https://anaconda.org/acellera/vina

**Comment by JimSEOW** [comment]
XGBoost for Win64 [status ](https://github.com/dmlc/xgboost/issues/4272#issuecomment-474039278)

**Comment by abster12** [comment]
Thanks I will try these and see if I can make some progress

**Comment by abster12** [comment]
The current test for Vina pose generation is actually supposed to work on linux only and changes need to be made to that.
